// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6LJk5-8ryoKMIY_6sTvqqEd7lnousLck',
    appId: '1:673043008139:web:48951563f2b44a4d6ee28e',
    messagingSenderId: '673043008139',
    projectId: 'firebaserealtime-352213',
    authDomain: 'fir-realtime-352213.firebaseapp.com',
    databaseURL: 'https://firebaserealtime-352213-default-rtdb.firebaseio.com',
    storageBucket: 'firebaserealtime-352213.appspot.com',
    measurementId: 'G-P3PNYBJ8LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7hVuRUDHXBQBiCPOCpjqMbtMcq2OaWvk',
    appId: '1:673043008139:android:2ace53945ec4bc9d6ee28e',
    messagingSenderId: '673043008139',
    projectId: 'firebaserealtime-352213',
    databaseURL: 'https://firebaserealtime-352213-default-rtdb.firebaseio.com',
    storageBucket: 'firebaserealtime-352213.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ0PZQKdVQZkzzaSMbyKGPGyAT3ifWxr0',
    appId: '1:673043008139:ios:e0013a268fc37d4d6ee28e',
    messagingSenderId: '673043008139',
    projectId: 'firebaserealtime-352213',
    databaseURL: 'https://firebaserealtime-352213-default-rtdb.firebaseio.com',
    storageBucket: 'firebaserealtime-352213.appspot.com',
    iosClientId: '673043008139-4mj5kulpkf91jcn2oud4rcilmill0jae.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasemlkit',
  );
}
